#ifndef Enum_h__
#define Enum_h__

enum RESOURCETYPE {RESOURCE_LOGO, RESOURCE_STAGE, RESOURCE_STATIC, RESOURCE_END};
enum COLLISIONID {COLLISION_CAMERA, COLLISION_AABB, COLLISION_OBB};
enum OBTAINTYPE{ OBTAIN_WALL1, OBTAIN_WALL2, OBTAIN_WALL3, OBTAIN_TOWER, OBTAIN_GATE, OBTAIN_HOME1, OBTAIN_HOME2, OBTAIN_HOME3, OBTAIN_TREE1, OBTAIN_TREE2 };
enum STATE_TYPE
{
	STATE_STAND,
	STATE_RUN_FRONT,
	STATE_RUN_BACK,
	STATE_RUN_RIGHT,
	STATE_RUN_LEFT,
	STATE_ATT_1,
	STATE_ATT_2,
	STATE_ATT_3,
	STATE_ATT_4,
	STATE_KNOCKBACK_1,
	STATE_KNOCKBACK_2,
	STATE_GETUP,
	STATE_SKILL_HARF,
	STATE_SKILL_CRESENT,
	STATE_SKILL_GREAT,
	STATE_DOWN,
	STATE_END
};

enum ORGE_STATE_TYPE
{
	ORGE_STATE_STAND,
	ORGE_STATE_RUN_FRONT,
	ORGE_STATE_ATT_1,
	ORGE_STATE_HITDAM,
	ORGE_STATE_KNOCKBACK,
	ORGE_STATE_BOUNCE,
	ORGE_STATE_DOWN,
	ORGE_STATE_GETUP,
	ORGE_STATE_END
};

enum GOBLIN_STATE_TYPE
{
	GOBLIN_STATE_STAND,
	GOBLIN_STATE_FRONTWALK,
	GOBLIN_STATE_ATT,
	GOBLIN_STATE_HIT,
	GOBLIN_STATE_KNOCKBACK,
	GOBLIN_STATE_DOWN,
	GOBLIN_STATE_GETUP,
	GOBLIN_STATE_END
};

enum BOSS_STATE_TYPE
{
	BOSS_STATE_STAND,
	BOSS_STATE_DASH,
	BOSS_STATE_BITE,
	BOSS_STATE_RIGHT_ATT,
	BOSS_STATE_LEFT_ATT,
	BOSS_STATE_FLY_START,
	BOSS_STATE_FLY_LOOP,
	BOSS_STATE_FLY_END,
	BOSS_STATE_TURN_RIGHT,
	BOSS_STATE_TURN_LEFT,
	BOSS_STATE_FIRE_START,
	BOSS_STATE_FIRE_LOOP,
	BOSS_STATE_FIRE_END,
	BOSS_STATE_DYE_START,
	BOSS_STATE_DYE_LOOP,
	BOSS_STATE_END
};

enum DOOR_STATE_TYPE
{
	DOOR_CLOSE,
	DOOR_OPENING,
	DOOR_OPEN,
	DOOR_CLOSING,
	DOOR_END
};

enum BOSS_BONE_TYPE
{
	BOSS_HAIR,
	BOSS_HEAD,
	BOSS_NECK1,
	BOSS_NECK2,
	BOSS_R_HAND,
	BOSS_L_HAND,
	BOSS_SPINE_1,
	BOSS_SPINE_2,
	BOSS_R_FOOT,
	BOSS_L_FOOT,
	BOSS_TAIL_1,
	BOSS_TAIL_2,
	BOSS_TAIL_3,
	BOSS_TAIL_4,
	BOSS_TAIL_5,
	BOSS_TAIL_6,
	BOSS_TAIL_7,
	BOSS_TAIL_8,
	BOSS_END
};
#endif // Enum_h__